### Site metadata

title: Artist's Portfolio
description: A gallery of images for an artist's portfolio, built with Jekyll

url: "https://gallery-blight.netlify.app"
baseurl: ""

github_username: "Cherno-Blight"
repository: "Cherno-Blight/Gallery"

google_analytics_key: ""

# For SEO tag.
logo: /siteicon.png
author:
  name: Blight/Cherno
  twitter:
social: https://discordapp.com/users/469617185552203786
  name: Artist's Portfolio
  links:
    - https://github.com/Cherno-Blight

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
  - Makefile
  - netlify.toml
